import { useEffect, useState } from "react";
import api from "../api/api";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";



export default function EnableMFA() {
  const [qrCode, setQrCode] = useState(null);
  const [otp, setOtp] = useState("");
  const [loadingQR, setLoadingQR] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchQR = async () => {
      try {
        const res = await api.post("/auth/mfa/setup/");
        setQrCode(res.data.qr_code);
      } catch (err) {
        toast.error("Failed to load QR code");
      } finally {
        setLoadingQR(false);
      }
    };
    fetchQR();
  }, []);

  const handleVerify = async () => {
    if (!otp || otp.length !== 6) {
      toast.error("Enter a valid 6-digit code");
      return;
    }
    try {
      await api.post("/auth/mfa/verify-setup/", { otp });
      toast.success("Two-Step verification activated");
      setTimeout(() => navigate("/profile"), 1200);
    } catch {
      toast.error("Invalid OTP code");
    }
  };

  return (
    <div style={styles.page}>
      <div style={styles.card}>
        
        {/* Header */}
        <div style={styles.header}>
          <h2 style={styles.title}>Secure Your Account</h2>
          <p style={styles.subtitle}>
            Protect your account with two-factor authentication.
          </p>
        </div>


        <div style={styles.instructionContainer}>
          <div style={styles.step}>
            <span style={styles.stepNumber}>1</span>
            <p style={styles.stepText}>Open your Authenticator app.</p>
          </div>

          <div style={styles.step}>
            <span style={styles.stepNumber}>2</span>
            <p style={styles.stepText}>
              Scan the QR code below to link your account.
            </p>
          </div>

          <div style={{ ...styles.step, marginBottom: 0 }}>
            <span style={styles.stepNumber}>3</span>
            <p style={styles.stepText}>
              Enter the 6-digit code generated by the app.
            </p>
          </div>
        </div>

        {/* QR Section */}
        <div style={styles.qrSection}>
          {loadingQR ? (
            <div style={styles.loadingPulse}>Generating Secure Key...</div>
          ) : (
            qrCode && (
              <div style={styles.qrWrapper}>
                <img
                  src={`data:image/png;base64,${qrCode}`}
                  alt="MFA QR"
                  style={styles.qrImage}
                />
              </div>
            )
          )}
        </div>

        {/* Verification Section */}
        <div style={styles.verifySection}>
          <input
            type="text"
            placeholder=""
            maxLength={6}
            value={otp}
            onChange={(e) => setOtp(e.target.value.replace(/\D/g, ""))}
            style={styles.input}
          />

          <button style={styles.button} onClick={handleVerify}>
            Activate Verification
          </button>
          
          <button 
            style={styles.cancelButton} 
            onClick={() => navigate("/profile")}
          >
            Configure Later
          </button>
        </div>
      </div>
    </div>
  );
}

/* ================= STYLES ================= */

const styles = {
  page: {
    minHeight: "100vh",
    background: "#000000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Inter', sans-serif",
    padding: "24px",
  },

  card: {
    width: "100%",
    maxWidth: "440px",
    padding: "48px 40px",
    borderRadius: "24px",
    background: "#0d0d0d",
    border: "1px solid #1f1f1f",
    boxShadow: "0 20px 50px rgba(0,0,0,0.5)",
    textAlign: "center",
    color: "#ffffff",
  },

  header: {
    marginBottom: "32px",
  },

  title: {
    fontSize: "24px",
    fontWeight: "700",
    marginBottom: "10px",
    letterSpacing: "-0.5px",
  },

  subtitle: {
    fontSize: "15px",
    color: "#9ca3af",
    lineHeight: "1.5",
  },

  instructionContainer: {
    textAlign: "left",
    marginBottom: "32px",
    background: "#161616",
    padding: "16px",
    borderRadius: "12px",
    border: "1px solid #222",
  },

  step: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    marginBottom: "12px",
  },

  stepNumber: {
    background: "#22c55e",
    color: "#000",
    fontSize: "11px",
    fontWeight: "800",
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: "2px",
  },

  stepText: {
    fontSize: "13px",
    color: "#d1d5db",
    margin: 0,
    lineHeight: "1.4",
  },

  qrSection: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "32px",
  },

  qrWrapper: {
    padding: "4px",
    background: "#ffffff",
    borderRadius: "1px",
    boxShadow: "0 0 40px rgba(34, 197, 94, 0.15)",
  },

  qrImage: {
    width: "180px",
    height: "180px",
    display: "block",
  },

  loadingPulse: {
    height: "180px",
    display: "flex",
    alignItems: "center",
    fontSize: "14px",
    color: "#4b5563",
  },

  verifySection: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
  },

  input: {
    marginTop: "8px",
    marginBottom: "20px",
    width: "100%",
    padding: "16px",
    fontSize: "24px",
    textAlign: "center",
    letterSpacing: "8px",
    borderRadius: "12px",
    border: "1px solid #2d2d2d",
    background: "#000000",
    color: "#ffffff",
    fontWeight: "600",
    outline: "none",
    transition: "border-color 0.2s ease",
  },

  button: {
    width: "100%",
    padding: "16px",
    borderRadius: "12px",
    border: "none",
    fontSize: "15px",
    fontWeight: "600",
    background: "#22c55e",
    color: "#000",
    cursor: "pointer",
    transition: "transform 0.1s ease, background 0.2s ease",
  },

  cancelButton: {
    background: "transparent",
    border: "none",
    color: "#6b7280",
    fontSize: "13px",
    marginTop: "16px",
    cursor: "pointer",
    textDecoration: "underline",
    textAlign: "center",
  },
};